// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: relation_info_base.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_relation_5finfo_5fbase_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_relation_5finfo_5fbase_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_relation_5finfo_5fbase_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_relation_5finfo_5fbase_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_relation_5finfo_5fbase_2eproto;
namespace ssp {
class RelationBase;
struct RelationBaseDefaultTypeInternal;
extern RelationBaseDefaultTypeInternal _RelationBase_default_instance_;
}  // namespace ssp
PROTOBUF_NAMESPACE_OPEN
template<> ::ssp::RelationBase* Arena::CreateMaybeMessage<::ssp::RelationBase>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ssp {

// ===================================================================

class RelationBase final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ssp.RelationBase) */ {
 public:
  inline RelationBase() : RelationBase(nullptr) {}
  ~RelationBase() override;
  explicit constexpr RelationBase(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RelationBase(const RelationBase& from);
  RelationBase(RelationBase&& from) noexcept
    : RelationBase() {
    *this = ::std::move(from);
  }

  inline RelationBase& operator=(const RelationBase& from) {
    CopyFrom(from);
    return *this;
  }
  inline RelationBase& operator=(RelationBase&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RelationBase& default_instance() {
    return *internal_default_instance();
  }
  static inline const RelationBase* internal_default_instance() {
    return reinterpret_cast<const RelationBase*>(
               &_RelationBase_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RelationBase& a, RelationBase& b) {
    a.Swap(&b);
  }
  inline void Swap(RelationBase* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RelationBase* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RelationBase* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RelationBase>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RelationBase& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RelationBase& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RelationBase* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ssp.RelationBase";
  }
  protected:
  explicit RelationBase(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFriendUserIdFieldNumber = 3,
    kBlackUserIdFieldNumber = 4,
    kVerFieldNumber = 1,
    kUserIdFieldNumber = 2,
  };
  // repeated int32 friend_user_id = 3;
  int friend_user_id_size() const;
  private:
  int _internal_friend_user_id_size() const;
  public:
  void clear_friend_user_id();
  private:
  int32_t _internal_friend_user_id(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_friend_user_id() const;
  void _internal_add_friend_user_id(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_friend_user_id();
  public:
  int32_t friend_user_id(int index) const;
  void set_friend_user_id(int index, int32_t value);
  void add_friend_user_id(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      friend_user_id() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_friend_user_id();

  // repeated int32 black_user_id = 4;
  int black_user_id_size() const;
  private:
  int _internal_black_user_id_size() const;
  public:
  void clear_black_user_id();
  private:
  int32_t _internal_black_user_id(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_black_user_id() const;
  void _internal_add_black_user_id(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_black_user_id();
  public:
  int32_t black_user_id(int index) const;
  void set_black_user_id(int index, int32_t value);
  void add_black_user_id(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      black_user_id() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_black_user_id();

  // optional int32 ver = 1;
  bool has_ver() const;
  private:
  bool _internal_has_ver() const;
  public:
  void clear_ver();
  int32_t ver() const;
  void set_ver(int32_t value);
  private:
  int32_t _internal_ver() const;
  void _internal_set_ver(int32_t value);
  public:

  // optional int32 user_id = 2;
  bool has_user_id() const;
  private:
  bool _internal_has_user_id() const;
  public:
  void clear_user_id();
  int32_t user_id() const;
  void set_user_id(int32_t value);
  private:
  int32_t _internal_user_id() const;
  void _internal_set_user_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ssp.RelationBase)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > friend_user_id_;
  mutable std::atomic<int> _friend_user_id_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > black_user_id_;
  mutable std::atomic<int> _black_user_id_cached_byte_size_;
  int32_t ver_;
  int32_t user_id_;
  friend struct ::TableStruct_relation_5finfo_5fbase_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RelationBase

// optional int32 ver = 1;
inline bool RelationBase::_internal_has_ver() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RelationBase::has_ver() const {
  return _internal_has_ver();
}
inline void RelationBase::clear_ver() {
  ver_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline int32_t RelationBase::_internal_ver() const {
  return ver_;
}
inline int32_t RelationBase::ver() const {
  // @@protoc_insertion_point(field_get:ssp.RelationBase.ver)
  return _internal_ver();
}
inline void RelationBase::_internal_set_ver(int32_t value) {
  _has_bits_[0] |= 0x00000001u;
  ver_ = value;
}
inline void RelationBase::set_ver(int32_t value) {
  _internal_set_ver(value);
  // @@protoc_insertion_point(field_set:ssp.RelationBase.ver)
}

// optional int32 user_id = 2;
inline bool RelationBase::_internal_has_user_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RelationBase::has_user_id() const {
  return _internal_has_user_id();
}
inline void RelationBase::clear_user_id() {
  user_id_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline int32_t RelationBase::_internal_user_id() const {
  return user_id_;
}
inline int32_t RelationBase::user_id() const {
  // @@protoc_insertion_point(field_get:ssp.RelationBase.user_id)
  return _internal_user_id();
}
inline void RelationBase::_internal_set_user_id(int32_t value) {
  _has_bits_[0] |= 0x00000002u;
  user_id_ = value;
}
inline void RelationBase::set_user_id(int32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:ssp.RelationBase.user_id)
}

// repeated int32 friend_user_id = 3;
inline int RelationBase::_internal_friend_user_id_size() const {
  return friend_user_id_.size();
}
inline int RelationBase::friend_user_id_size() const {
  return _internal_friend_user_id_size();
}
inline void RelationBase::clear_friend_user_id() {
  friend_user_id_.Clear();
}
inline int32_t RelationBase::_internal_friend_user_id(int index) const {
  return friend_user_id_.Get(index);
}
inline int32_t RelationBase::friend_user_id(int index) const {
  // @@protoc_insertion_point(field_get:ssp.RelationBase.friend_user_id)
  return _internal_friend_user_id(index);
}
inline void RelationBase::set_friend_user_id(int index, int32_t value) {
  friend_user_id_.Set(index, value);
  // @@protoc_insertion_point(field_set:ssp.RelationBase.friend_user_id)
}
inline void RelationBase::_internal_add_friend_user_id(int32_t value) {
  friend_user_id_.Add(value);
}
inline void RelationBase::add_friend_user_id(int32_t value) {
  _internal_add_friend_user_id(value);
  // @@protoc_insertion_point(field_add:ssp.RelationBase.friend_user_id)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
RelationBase::_internal_friend_user_id() const {
  return friend_user_id_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
RelationBase::friend_user_id() const {
  // @@protoc_insertion_point(field_list:ssp.RelationBase.friend_user_id)
  return _internal_friend_user_id();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
RelationBase::_internal_mutable_friend_user_id() {
  return &friend_user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
RelationBase::mutable_friend_user_id() {
  // @@protoc_insertion_point(field_mutable_list:ssp.RelationBase.friend_user_id)
  return _internal_mutable_friend_user_id();
}

// repeated int32 black_user_id = 4;
inline int RelationBase::_internal_black_user_id_size() const {
  return black_user_id_.size();
}
inline int RelationBase::black_user_id_size() const {
  return _internal_black_user_id_size();
}
inline void RelationBase::clear_black_user_id() {
  black_user_id_.Clear();
}
inline int32_t RelationBase::_internal_black_user_id(int index) const {
  return black_user_id_.Get(index);
}
inline int32_t RelationBase::black_user_id(int index) const {
  // @@protoc_insertion_point(field_get:ssp.RelationBase.black_user_id)
  return _internal_black_user_id(index);
}
inline void RelationBase::set_black_user_id(int index, int32_t value) {
  black_user_id_.Set(index, value);
  // @@protoc_insertion_point(field_set:ssp.RelationBase.black_user_id)
}
inline void RelationBase::_internal_add_black_user_id(int32_t value) {
  black_user_id_.Add(value);
}
inline void RelationBase::add_black_user_id(int32_t value) {
  _internal_add_black_user_id(value);
  // @@protoc_insertion_point(field_add:ssp.RelationBase.black_user_id)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
RelationBase::_internal_black_user_id() const {
  return black_user_id_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
RelationBase::black_user_id() const {
  // @@protoc_insertion_point(field_list:ssp.RelationBase.black_user_id)
  return _internal_black_user_id();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
RelationBase::_internal_mutable_black_user_id() {
  return &black_user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
RelationBase::mutable_black_user_id() {
  // @@protoc_insertion_point(field_mutable_list:ssp.RelationBase.black_user_id)
  return _internal_mutable_black_user_id();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ssp

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_relation_5finfo_5fbase_2eproto
